version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: 'your-hostname'
    environment:
      TZ: "Asia/Ho_Chi_Minh"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://your-hostname'
        #Add any other gitlab.rb configuration here, each on its own line
        letsencrypt['enable'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        registry_external_url 'https://your-registry-hostname'

        #Reply by email
        gitlab_rails['incoming_email_enabled'] = true
        gitlab_rails['incoming_email_address'] = "username+%{key}@gmail.com"
        gitlab_rails['incoming_email_email'] = "username@gmail.com"
        gitlab_rails['incoming_email_password'] = "changeme"
        gitlab_rails['incoming_email_host'] = "imap.gmail.com"
        gitlab_rails['incoming_email_port'] = 993
        gitlab_rails['incoming_email_ssl'] = true
        gitlab_rails['incoming_email_start_tls'] = false
        gitlab_rails['incoming_email_mailbox_name'] = "inbox"
        gitlab_rails['incoming_email_idle_timeout'] = 60
        gitlab_rails['incoming_email_delete_after_delivery'] = true
        gitlab_rails['incoming_email_expunge_deleted'] = true
        gitlab_rails['incoming_email_delivery_method'] = "sidekiq"
        gitlab_rails['service_desk_email_delivery_method'] = "sidekiq"

        #SMTP
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "username@gmail.com"
        gitlab_rails['smtp_password'] = "changeme"
        gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true

        #LDAP
        gitlab_rails['ldap_group_sync_worker_cron'] = "0 */2 * * *"
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_servers'] = {
          'main' => {
            'label' => 'FLGVN AD',
            'host' =>  'AZVNADDC01.CAWOWX.local',
            'port' => 636,
            'uid' => 'sAMAccountName',
            'encryption' => 'simple_tls',
            'verify_certificates' => false,
            'bind_dn' => 'GitLabSRV',
            'password' => 'changeme',
            'base' => 'OU=VTN,DC=CAWOWX,DC=local',
           }
         }
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - './data/config:/etc/gitlab'
      - './data/logs:/var/log/gitlab'
      - './data/data:/var/opt/gitlab'
      #Stored the ssl files and edit to the same domain name
      - './ssl:/etc/gitlab/ssl'
